$ANSIBLE_VAULT;1.1;AES256
38303264396237623762616361326564373836303465613563663935643735386539343334353861
3161666136323365643033353330353661616434376637300a363235366234343838633361613138
33396538363463333736663563663231393739343464666334666437356534383063353861373330
6261343864646234370a376138666265396362383630346665393837313936636635656263643366
31343833333834636537303137643838633033366236636362313534353662386539313530363135
3234303739363666376233343231646637646266666332376362